CREATE DATABASE TEST_DB;
USE DATABASE TEST_DB;

CREATE TABLE CUSTOMER_DETAILS (
    first_name STRING,
    last_name STRING,
    address STRING,
    city STRING,
    state STRING
);

SELECT * FROM CUSTOMER_DETAILS;

CREATE OR REPLACE FILE FORMAT PIPE_FORMAT_CLI
	type = 'CSV'
	field_delimiter = '|'
	skip_header = 1;
	
CREATE OR REPLACE STAGE PIP_CLI_STAGE
	file_format = PIP_FORMAT_CLI;	

put
file://C:\Users\snowflake_project\Data\customer_detail.csv
@PIP_CLI_STAGE auto_compress=true;

list @PIP_CLI_STAGE;

COPY INTO CUSTOMER_DETAILS
	FROM @PIP_CLI_STAGE
	file_format = (format_name = PIP_FORMAT_CLI)
	on_error = 'skip_file';
	
COPY INTO mycsvtable
	FROM @mycsvstage
	file_format = (format_name = PIP_FORMAT_CLI)
	pattern = '*.contain[1-5].csv.gz'
	on_error = 'skip_file';


CREATE OR REPLACE TABLE TESLA_STOCKS(
    date DATE,
    open_value DOUBLE,
    high_vlaue DOUBLE,
    low_value DOUBLE,
    close_vlaue DOUBLE,
    adj_close_value DOUBLE,
    volume BIGINT
);

SELECT * FROM TESLA_STOCKS;

CREATE OR REPLACE STAGE BULK_COPY_TESLA_STOCKS
URL = "s3://snowflake-loading-smit/TSLA.csv"
CREDENTIALS = (AWS_KEY_ID='', AWS_SECRET_KEY='');

LIST @BULK_COPY_TESLA_STOCKS;

COPY INTO TESLA_STOCKS
	FROM @BULK_COPY_TESLA_STOCKS
	file_format = (TYPE = 'CSV', FIELD_DELIMITER=',', SKIP_HEADER=1)
    on_error = 'skip_file';

SELECT * FROM TESLA_STOCKS;

USE ROLE ACCOUNTADMIN;
GRANT CREATE INTEGRATION ON ACCOUNT TO SYSADMIN;
USE ROLE SYSADMIN;

CREATE OR REPLACE STORAGE INTEGRATION S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::767398088866:role/snowflake-s3-role'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('s3://snowflake-loading-smit/TSLA.csv');

USE ROLE ACCOUNTADMIN;
GRANT USAGE ON INTEGRATION S3_INTEGRATION TO ROLE SYSADMIN;
USE ROLE SYSADMIN;

DESC INTEGRATION S3_INTEGRATION;

CREATE OR REPLACE STAGE S3_INTEGRATEION_BULK_COPY_TESLA_STOCKS
  STORAGE_INTEGRATION = S3_INTEGRATION
  URL = 's3://snowflake-loading-smit/TSLA.csv'
  FILE_FORMAT = (TYPE = 'CSV', FIELD_DELIMITER=',', SKIP_HEADER=1);

LIST @S3_INTEGRATEION_BULK_COPY_TESLA_STOCKS;

TRUNCATE TABLE TESLA_STOCKS;
SELECT * FROM TESLA_STOCKS;

COPY INTO TESLA_STOCKS FROM @S3_INTEGRATEION_BULK_COPY_TESLA_STOCKS;

SELECT * FROM TESLA_STOCKS;

TRUNCATE TABLE TESLA_STOCKS;

DROP STORAGE INTEGRATION S3_INTEGRATION;
DROP STAGE S3_INTEGRATEION_BULK_COPY_TESLA_STOCKS;

CREATE OR REPLACE STORAGE INTEGRATION S3_TESLA_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::767398088866:role/snowflake-s3-role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://snowflake-loading-smit/TSLA.csv');

DESC INTEGRATION S3_TESLA_INTEGRATION;

CREATE OR REPLACE FILE FORMAT S3_TESLA_STAGE_FORMAT
    TYPE= 'CSV'
    FIELD_DELIMITER=','
    SKIP_HEADER=1;

CREATE STAGE S3_TESLA_STAGE
  STORAGE_INTEGRATION = S3_TESLA_INTEGRATION
  URL = 's3://snowflake-loading-smit/TSLA.csv'
  FILE_FORMAT = S3_TESLA_STAGE_FORMAT;

COPY INTO TESLA_STOCKS FROM @S3_TESLA_STAGE;

SELECT * FROM TESLA_STOCKS;
TRUNCATE TABLE TESLA_STOCKS;

CREATE OR REPLACE PIPE S3_TESLA_PIPE
AUTO_INGEST=TRUE
AS
COPY INTO TESLA_STOCKS FROM @S3_TESLA_STAGE;

SHOW PIPES;

SELECT * FROM TESLA_STOCKS;
select count(*) from tesla_stocks;

DROP PIPE S3_TESLA_PIPE;

SELECT * FROM TESLA_STOCKS order by DATE desc;

DROP TABLE TESLA_STOCKS;
UNDROP TABLE TESLA_STOCKS;